version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: /
    update_schedule: live
    target_branch: dev

    default_labels:
      - dependencies

    version_requirement_updates: auto
  - package_manager: javascript
    directory: /
    update_schedule: live
    target_branch: dev

    default_labels:
      - dependencies
